[package]
name = "debug"
version = "0.1.0"
edition = "2024"
authors = ["Nihal Pasham <nihalp@nvidia.com>"]
license = "Apache-2.0"

[workspace]

[dependencies]
cuda-core = "0.3.1"
cuda-macros = { path = "../../../../crates/cuda-macros" }
cuda-device = { path = "../../../../crates/cuda-device" }
cuda-host = { path = "../../../../crates/cuda-host" }
