/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! Kernel launch infrastructure with rust-analyzer type hint support.
//!
//! This module provides traits and helpers for launching CUDA kernels with
//! full IDE type checking. The key insight is separating concerns:
//!
//! - **Macro** (`cuda_launch!`): Captures kernel identifier → PTX name string,
//!   marshals arguments into a `Vec<*mut c_void>`, and calls
//!   `cuda_core::launch_kernel` directly. The macro is caller-unsafe: it
//!   cannot check argument count, types, or whether the raw launch geometry
//!   matches the kernel's indexing assumptions, so every use must sit inside
//!   an `unsafe { }` block. Prefer `#[cuda_module]` with a launch contract for
//!   kernels embedded in your own crate.
//! - **Traits** (`CudaKernel`, `GenericCudaKernel`): Provide PTX entry-point
//!   names for rust-analyzer and compile-time validation.

use std::ffi::c_void;
#[cfg(feature = "async")]
use std::future::IntoFuture;
#[cfg(feature = "async")]
use std::sync::Arc;

// =============================================================================
// Core Traits
// =============================================================================

/// Trait implemented by kernel functions.
///
/// This trait is automatically generated by the `#[kernel]` attribute macro.
/// It provides the PTX entry point name for runtime kernel lookup.
///
/// # Example
///
/// When you write:
/// ```ignore
/// #[kernel]
/// pub fn vecadd(a: &[f32], b: &[f32], mut c: DisjointSlice<f32>) { ... }
/// ```
///
/// The macro generates (on host side only):
/// ```ignore
/// pub struct __vecadd_CudaKernel;
/// impl CudaKernel for __vecadd_CudaKernel {
///     const PTX_NAME: &'static str = "vecadd";  // Original function name
/// }
/// ```
///
/// Note: the function is renamed internally to `cuda_oxide_kernel_<hash>_vecadd`
/// for detection by the compiler backend (the prefix is owned by the
/// workspace-internal `reserved-oxide-symbols` crate), but the PTX entry point
/// uses the original name.
pub trait CudaKernel {
    /// The PTX entry point name (e.g., "vecadd" - the original function name)
    const PTX_NAME: &'static str;
}

/// Trait for generic kernel functions.
///
/// Unlike `CudaKernel`, this trait provides a function to get the PTX name
/// because generic kernels have different PTX names for each type/const
/// specialization.
///
/// # Example
///
/// For a generic kernel:
/// ```ignore
/// #[kernel]
/// pub fn scale<T: Copy + Mul<Output = T>>(factor: T, input: &[T], mut out: DisjointSlice<T>) { ... }
/// ```
///
/// Application code asks the generated helper for a concrete specialization:
/// ```ignore
/// let name = scale_ptx_name::<f32>();
/// // "scale_TID_<32 lowercase hex characters>"
/// ```
///
/// `#[kernel]` implements this trait on an internal marker type and exposes
/// the helper above. Application code should use the helper rather than name
/// that marker directly. The helper also retains the requested specialization
/// in device output before it returns the lookup name.
///
/// # PTX Naming Scheme
///
/// Generic kernels are named `<base>_TID_<hex32>`, where `<hex32>` hashes the
/// concrete generated kernel function-item type. That `FnDef` contains the
/// function identity plus every ordered type and const argument. The host uses
/// `cuda_host::type_id_u128_of_val(&kernel_entry::<T, N>)`; the backend hashes
/// `Instance::ty` for the same entry. Both use rustc's region-erasing stable
/// type hash, so lifetimes do not create spurious PTX variants and the name
/// remains fixed-length regardless of generic arity.
///
/// The bound on `ptx_name` is intentionally just whatever the kernel
/// itself declared — typically `Copy` on the value-passed generics. No
/// `'static` is added: the helper `cuda_host::type_id_u128` uses
/// `core::intrinsics::type_id`, which is bound `T: ?Sized` rather than
/// `T: 'static`, so closures that borrow non-`'static` data still go
/// through the typed launch path (just like they did under the legacy
/// `type_name`-based scheme).
pub trait GenericCudaKernel {
    /// Get the PTX entry point name for this specific instantiation.
    ///
    /// Unlike `CudaKernel::PTX_NAME`, this is a function because the name
    /// depends on the concrete type and const specialization.
    fn ptx_name() -> &'static str;
}

// =============================================================================
// Typed Kernel Arguments
// =============================================================================

/// Marker trait for values that may be passed to a CUDA kernel by value.
///
/// `#[cuda_module]` uses this trait for scalar kernel parameters. Any `Copy`
/// value can be used here because cuda-oxide compiles the host and device
/// instantiations from the same Rust type. Prefer `#[repr(C)]` for structs that
/// must also interoperate with CUDA C/C++ code.
pub trait KernelScalar: Copy {}

impl<T: Copy> KernelScalar for T {}

/// Pushes a by-value scalar kernel argument into a CUDA driver argument list.
///
/// The pointed-to value must remain alive until the launch submission call has
/// returned. The generated `#[cuda_module]` launch methods create stack locals
/// for this purpose before calling this helper.
///
/// # Zero-sized values
///
/// `T` is allowed to be zero-sized (e.g. a closure with no captures, a unit
/// struct). When `size_of::<T>() == 0` the backend drops the corresponding
/// `.param` entirely from the kernel's PTX entry point — the CUDA driver
/// reads no bytes for it — so we must also skip the host push to keep the
/// driver's `kernelParams[]` indices aligned with the kernel's declared
/// parameters. The check is a `const`-fold for monomorphized types and
/// disappears in release builds for non-ZSTs.
#[inline]
#[doc(hidden)]
pub fn push_kernel_scalar<T: KernelScalar>(args: &mut Vec<*mut c_void>, value: &mut T) {
    if std::mem::size_of::<T>() == 0 {
        return;
    }
    args.push(value as *mut T as *mut c_void);
}

/// Returns the `(device pointer, element count)` pair used for read-only slice
/// parameters such as `&[T]`.
#[inline]
#[doc(hidden)]
pub fn read_only_device_buffer_arg<T>(
    buffer: &cuda_core::DeviceBuffer<T>,
) -> (cuda_core::sys::CUdeviceptr, u64) {
    (buffer.cu_deviceptr(), buffer.len() as u64)
}

/// Returns the `(device pointer, element count)` pair used for writable slice
/// parameters such as `&mut [T]` and `DisjointSlice<T>`.
#[inline]
#[doc(hidden)]
pub fn writable_device_buffer_arg<T>(
    buffer: &mut cuda_core::DeviceBuffer<T>,
) -> (cuda_core::sys::CUdeviceptr, u64) {
    (buffer.cu_deviceptr(), buffer.len() as u64)
}

/// Pushes a device slice argument pair into a CUDA driver argument list.
///
/// cuda-oxide device slices lower to two kernel parameters: `CUdeviceptr` and
/// `u64` element count. Keeping that encoding here makes the generated
/// `#[cuda_module]` methods target a stable helper instead of open-coding the
/// ABI in every expansion.
#[inline]
#[doc(hidden)]
pub fn push_kernel_device_slice(
    args: &mut Vec<*mut c_void>,
    ptr: &mut cuda_core::sys::CUdeviceptr,
    len: &mut u64,
) {
    args.push(ptr as *mut cuda_core::sys::CUdeviceptr as *mut c_void);
    args.push(len as *mut u64 as *mut c_void);
}

/// A device buffer together with the row width the kernel will index it by.
///
/// Kernels whose index space fixes the row width in the type need nothing
/// here. A kernel taking `DisjointSlice<T, RuntimeRowMajorTiles<R, C>>` or
/// `DisjointSlice<T, Runtime2DIndex>` reads its row width from the slice, and
/// this is where that width is supplied.
///
/// Binding the row width on the host is what makes the device-side accessor
/// safe. One value is written into the launch packet, so every thread reads
/// the same row width and distinct thread coordinates map to disjoint tiles.
/// A width passed per call could not give that: device code can select between
/// two launch-uniform values under a thread-varying condition, and two threads
/// then resolve the same element.
///
/// ```rust,ignore
/// kernels::sgemm(&stream, cfg, m, k, alpha, &a, &b, RowWidth::new(&mut c, n))?;
/// ```
pub struct RowWidth<'a, T> {
    buffer: &'a mut cuda_core::DeviceBuffer<T>,
    width: u32,
}

impl<'a, T> RowWidth<'a, T> {
    /// Bind `width` as the row width for this launch's view of `buffer`.
    ///
    /// `width` is a count of elements, not bytes.
    #[inline]
    pub fn new(buffer: &'a mut cuda_core::DeviceBuffer<T>, width: u32) -> Self {
        RowWidth { buffer, width }
    }

    /// The row width bound here, in elements.
    #[inline]
    pub fn width(&self) -> u32 {
        self.width
    }

    /// The element count of the bound buffer.
    ///
    /// A `requires` clause naming `c.len()` resolves here, so a size relation
    /// reads the same whether or not the slice carries a row width.
    #[inline]
    pub fn len(&self) -> usize {
        self.buffer.len()
    }

    /// Whether the bound buffer is empty.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.buffer.len() == 0
    }
}

/// An owned device buffer together with the row width the kernel indexes it by.
///
/// The owned counterpart of [`RowWidth`], for the async launch flavours that
/// take ownership of their buffers so the allocation outlives the launch. The
/// row width binds the same way and for the same reason.
pub struct RowWidthOwned<B> {
    buffer: B,
    width: u32,
}

impl<B> RowWidthOwned<B> {
    /// Bind `width` as the row width for this launch's view of `buffer`.
    ///
    /// `width` is a count of elements, not bytes.
    #[inline]
    pub fn new(buffer: B, width: u32) -> Self {
        RowWidthOwned { buffer, width }
    }

    /// The row width bound here, in elements.
    #[inline]
    pub fn width(&self) -> u32 {
        self.width
    }

    /// The buffer this row width was bound to.
    #[inline]
    pub fn buffer(&self) -> &B {
        &self.buffer
    }

    /// Recover the buffer, dropping the binding.
    ///
    /// An owned async launch hands its resources back when it completes, so a
    /// later stage that no longer indexes by rows takes the buffer out here.
    #[inline]
    pub fn into_buffer(self) -> B {
        self.buffer
    }
}

/// Returns the `(device pointer, element count, row width)` triple used for
/// writable slice parameters whose index space carries a runtime row width.
#[inline]
#[doc(hidden)]
pub fn row_width_device_buffer_arg<T>(
    bound: RowWidth<'_, T>,
) -> (cuda_core::sys::CUdeviceptr, u64, u32) {
    (
        bound.buffer.cu_deviceptr(),
        bound.buffer.len() as u64,
        bound.width,
    )
}

/// Pushes a row-width device slice argument triple into a driver argument
/// list.
///
/// A slice over an index space with a runtime row width lowers to three kernel
/// parameters: `CUdeviceptr`, `u64` element count and `u32` row width,
/// matching the `{ ptr, len, space }` layout of the device-side
/// `DisjointSlice`.
#[inline]
#[doc(hidden)]
pub fn push_kernel_row_width_device_slice(
    args: &mut Vec<*mut c_void>,
    ptr: &mut cuda_core::sys::CUdeviceptr,
    len: &mut u64,
    width: &mut u32,
) {
    args.push(ptr as *mut cuda_core::sys::CUdeviceptr as *mut c_void);
    args.push(len as *mut u64 as *mut c_void);
    args.push(width as *mut u32 as *mut c_void);
}

// =============================================================================
// Typed Async Kernel Arguments
// =============================================================================

/// A typed device allocation that can be passed to an async kernel launch as a
/// read-only device slice.
///
/// # Safety
///
/// For a nonzero byte extent, every value returned by
/// [`cu_deviceptr`](Self::cu_deviceptr) must identify a live, correctly aligned
/// device allocation covering at least `len()` consecutive `Elem` values. The
/// allocation must remain valid for the full borrow or owned operation in
/// which this value is used. When used as a read-only `KernelSliceArg`, the
/// reported range must obey Rust's shared-reference rules: it cannot be
/// mutated except through `UnsafeCell`-based or atomic element types under
/// their synchronization contract.
///
/// Implementing this trait is unsafe because generated launch methods trust
/// the pointer and length without inspecting the allocation:
///
/// ```compile_fail,E0200
/// use cuda_host::KernelSliceArg;
///
/// struct Fake;
///
/// impl KernelSliceArg for Fake {
///     type Elem = u32;
///     fn cu_deviceptr(&self) -> cuda_core::sys::CUdeviceptr { 1 }
///     fn len(&self) -> usize { 1_000_000 }
/// }
/// ```
#[cfg(feature = "async")]
pub unsafe trait KernelSliceArg {
    /// Element type stored in the allocation.
    type Elem;

    /// Returns the raw CUDA device pointer for the allocation.
    fn cu_deviceptr(&self) -> cuda_core::sys::CUdeviceptr;

    /// Returns the number of `T` elements in the allocation.
    fn len(&self) -> usize;

    /// Returns true when the allocation has zero elements.
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

/// A typed device allocation that can be passed to an async kernel launch as a
/// writable device slice.
///
/// # Safety
///
/// The pointer, extent, alignment, and lifetime requirements from
/// [`KernelSliceArg`] still apply. Its shared-read restriction is replaced by
/// this rule: the implementor must own exclusive device-write authority for
/// the entire reported element range for the lifetime of the mutable borrow or
/// owned operation.
#[cfg(feature = "async")]
pub unsafe trait KernelSliceArgMut: KernelSliceArg {}

#[cfg(feature = "async")]
// SAFETY: DeviceBuffer owns the reported allocation and keeps its CUDA context
// alive; its pointer and length accessors describe that allocation exactly.
unsafe impl<T> KernelSliceArg for cuda_core::DeviceBuffer<T> {
    type Elem = T;

    fn cu_deviceptr(&self) -> cuda_core::sys::CUdeviceptr {
        self.cu_deviceptr()
    }

    fn len(&self) -> usize {
        self.len()
    }
}

#[cfg(feature = "async")]
// SAFETY: &mut DeviceBuffer provides exclusive host authority to launch device
// writes through this adapter for the duration of the operation.
unsafe impl<T> KernelSliceArgMut for cuda_core::DeviceBuffer<T> {}

#[cfg(feature = "async")]
// SAFETY: DeviceBox owns the reported allocation and its raw constructor
// requires the pointer, element count, and device ordinal to be truthful.
unsafe impl<T: Send> KernelSliceArg for cuda_async::simt::device_box::DeviceBox<[T]> {
    type Elem = T;

    fn cu_deviceptr(&self) -> cuda_core::sys::CUdeviceptr {
        self.cu_deviceptr()
    }

    fn len(&self) -> usize {
        self.len()
    }
}

#[cfg(feature = "async")]
// SAFETY: &mut DeviceBox provides exclusive host authority to launch device
// writes through this adapter for the duration of the operation.
unsafe impl<T: Send> KernelSliceArgMut for cuda_async::simt::device_box::DeviceBox<[T]> {}

#[cfg(feature = "async")]
// SAFETY: Arc only extends the lifetime of B and delegates both truthful
// accessors unchanged to B's unsafe implementation.
unsafe impl<B> KernelSliceArg for Arc<B>
where
    B: KernelSliceArg + ?Sized,
{
    type Elem = B::Elem;

    fn cu_deviceptr(&self) -> cuda_core::sys::CUdeviceptr {
        self.as_ref().cu_deviceptr()
    }

    fn len(&self) -> usize {
        self.as_ref().len()
    }
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn new_async_kernel_launch_builder<'a>(
    func: cuda_core::CudaFunction,
) -> cuda_async::simt::launch::AsyncKernelLaunchBuilder<'a> {
    cuda_async::simt::launch::AsyncKernelLaunchBuilder::new(Arc::new(func))
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn new_owned_async_kernel_launch<R: Send>(
    launch: cuda_async::simt::launch::AsyncKernelLaunch<'static>,
    resources: R,
) -> cuda_async::simt::launch::OwnedAsyncKernelLaunch<R> {
    cuda_async::simt::launch::OwnedAsyncKernelLaunch::new(launch, resources)
}

/// Async operation carrying a validated, kernel-branded launch.
///
/// The underlying [`cuda_async::simt::launch::AsyncKernelLaunch`] is immutable after
/// its builder is finalized. This wrapper additionally carries the prepared
/// contract and checks the stream selected by the async scheduler against the
/// prepared function's CUDA context immediately before submission.
#[cfg(feature = "async")]
pub struct PreparedAsyncKernelLaunch<'a, Contract>
where
    Contract: cuda_core::KernelLaunchContract,
{
    launch: cuda_async::simt::launch::AsyncKernelLaunch<'a>,
    prepared: cuda_core::PreparedLaunch<Contract>,
}

#[cfg(feature = "async")]
impl<Contract> std::fmt::Debug for PreparedAsyncKernelLaunch<'_, Contract>
where
    Contract: cuda_core::KernelLaunchContract,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PreparedAsyncKernelLaunch")
            .field("contract", &Contract::SPEC.kernel_name())
            .finish_non_exhaustive()
    }
}

/// Owns async kernel resources while preserving an immutable prepared launch.
#[cfg(feature = "async")]
pub struct PreparedOwnedAsyncKernelLaunch<R, Contract>
where
    R: Send,
    Contract: cuda_core::KernelLaunchContract,
{
    launch: cuda_async::simt::launch::OwnedAsyncKernelLaunch<R>,
    prepared: cuda_core::PreparedLaunch<Contract>,
}

#[cfg(feature = "async")]
impl<R, Contract> std::fmt::Debug for PreparedOwnedAsyncKernelLaunch<R, Contract>
where
    R: Send,
    Contract: cuda_core::KernelLaunchContract,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PreparedOwnedAsyncKernelLaunch")
            .field("contract", &Contract::SPEC.kernel_name())
            .finish_non_exhaustive()
    }
}

/// Seals a fully marshalled async launch behind its prepared contract.
///
/// # Safety
///
/// `launch` must contain the same function and raw launch configuration as
/// `prepared`, with the cluster/cooperative mode declared by its contract.
#[doc(hidden)]
#[cfg(feature = "async")]
pub unsafe fn new_prepared_async_kernel_launch<'a, Contract>(
    launch: cuda_async::simt::launch::AsyncKernelLaunch<'a>,
    prepared: cuda_core::PreparedLaunch<Contract>,
) -> PreparedAsyncKernelLaunch<'a, Contract>
where
    Contract: cuda_core::KernelLaunchContract,
{
    PreparedAsyncKernelLaunch { launch, prepared }
}

/// Seals a fully marshalled owned async launch behind its prepared contract.
///
/// # Safety
///
/// `launch` must contain the same function and raw launch configuration as
/// `prepared`, with the cluster/cooperative mode declared by its contract.
#[doc(hidden)]
#[cfg(feature = "async")]
pub unsafe fn new_prepared_owned_async_kernel_launch<R, Contract>(
    launch: cuda_async::simt::launch::OwnedAsyncKernelLaunch<R>,
    prepared: cuda_core::PreparedLaunch<Contract>,
) -> PreparedOwnedAsyncKernelLaunch<R, Contract>
where
    R: Send,
    Contract: cuda_core::KernelLaunchContract,
{
    PreparedOwnedAsyncKernelLaunch { launch, prepared }
}

#[cfg(feature = "async")]
impl<'a, Contract> cuda_async::simt::device_operation::DeviceOperation
    for PreparedAsyncKernelLaunch<'a, Contract>
where
    Contract: cuda_core::KernelLaunchContract,
{
    type Output = ();

    unsafe fn execute(
        self,
        context: &cuda_async::simt::device_operation::ExecutionContext,
    ) -> Result<(), cuda_async::simt::error::DeviceError> {
        self.prepared
            .validate_stream(context.get_cuda_stream())
            .map_err(|error| cuda_async::simt::error::DeviceError::Launch(error.to_string()))?;
        unsafe {
            cuda_async::simt::device_operation::DeviceOperation::execute(self.launch, context)
        }
    }
}

#[cfg(feature = "async")]
impl<'a, Contract> IntoFuture for PreparedAsyncKernelLaunch<'a, Contract>
where
    Contract: cuda_core::KernelLaunchContract,
{
    type Output = Result<(), cuda_async::simt::error::DeviceError>;
    type IntoFuture = cuda_async::simt::device_future::DeviceFuture<(), Self>;

    fn into_future(self) -> Self::IntoFuture {
        match cuda_async::simt::device_context::with_default_device_policy(|policy| {
            cuda_async::simt::scheduling_policies::SchedulingPolicy::schedule(policy, self)
        }) {
            Ok(Ok(future)) => future,
            Ok(Err(error)) | Err(error) => {
                cuda_async::simt::device_future::DeviceFuture::failed(error)
            }
        }
    }
}

#[cfg(feature = "async")]
impl<R, Contract> cuda_async::simt::device_operation::DeviceOperation
    for PreparedOwnedAsyncKernelLaunch<R, Contract>
where
    R: Send + 'static,
    Contract: cuda_core::KernelLaunchContract,
{
    type Output = R;

    unsafe fn execute(
        self,
        context: &cuda_async::simt::device_operation::ExecutionContext,
    ) -> Result<R, cuda_async::simt::error::DeviceError> {
        self.prepared
            .validate_stream(context.get_cuda_stream())
            .map_err(|error| cuda_async::simt::error::DeviceError::Launch(error.to_string()))?;
        unsafe {
            cuda_async::simt::device_operation::DeviceOperation::execute(self.launch, context)
        }
    }
}

#[cfg(feature = "async")]
impl<R, Contract> IntoFuture for PreparedOwnedAsyncKernelLaunch<R, Contract>
where
    R: Send + 'static,
    Contract: cuda_core::KernelLaunchContract,
{
    type Output = Result<R, cuda_async::simt::error::DeviceError>;
    type IntoFuture = cuda_async::simt::device_future::DeviceFuture<R, Self>;

    fn into_future(self) -> Self::IntoFuture {
        match cuda_async::simt::device_context::with_default_device_policy(|policy| {
            cuda_async::simt::scheduling_policies::SchedulingPolicy::schedule(policy, self)
        }) {
            Ok(Ok(future)) => future,
            Ok(Err(error)) | Err(error) => {
                cuda_async::simt::device_future::DeviceFuture::failed(error)
            }
        }
    }
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn set_async_kernel_cluster_dim(
    launch: &mut cuda_async::simt::launch::AsyncKernelLaunchBuilder<'_>,
    cluster_dim: (u32, u32, u32),
) {
    launch.set_cluster_dim(cluster_dim);
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn set_async_kernel_cooperative(
    launch: &mut cuda_async::simt::launch::AsyncKernelLaunchBuilder<'_>,
    cooperative: bool,
) {
    launch.set_cooperative(cooperative);
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn push_async_kernel_scalar<'a, T: KernelScalar + 'a>(
    launch: &mut cuda_async::simt::launch::AsyncKernelLaunchBuilder<'a>,
    value: T,
) {
    if std::mem::size_of::<T>() != 0 {
        launch.push_scalar_arg(value);
    }
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn push_async_read_only_device_slice<B>(
    launch: &mut cuda_async::simt::launch::AsyncKernelLaunchBuilder<'_>,
    buffer: &B,
) where
    B: KernelSliceArg + ?Sized,
{
    launch.push_scalar_arg(buffer.cu_deviceptr());
    launch.push_scalar_arg(buffer.len() as u64);
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn push_async_writable_device_slice<B>(
    launch: &mut cuda_async::simt::launch::AsyncKernelLaunchBuilder<'_>,
    buffer: &mut B,
) where
    B: KernelSliceArgMut + ?Sized,
{
    launch.push_scalar_arg(buffer.cu_deviceptr());
    launch.push_scalar_arg(buffer.len() as u64);
}

/// Pushes a row-width device slice as three async kernel arguments.
///
/// Matches the `{ ptr, len, space }` layout of a device-side `DisjointSlice`
/// whose index space carries a runtime row width.
#[doc(hidden)]
#[cfg(feature = "async")]
pub fn push_async_row_width_device_slice<T>(
    launch: &mut cuda_async::simt::launch::AsyncKernelLaunchBuilder<'_>,
    bound: RowWidth<'_, T>,
) {
    let (ptr, len, width) = row_width_device_buffer_arg(bound);
    launch.push_scalar_arg(ptr);
    launch.push_scalar_arg(len);
    launch.push_scalar_arg(width);
}

/// Pushes an owned row-width device slice as three async kernel arguments.
#[doc(hidden)]
#[cfg(feature = "async")]
pub fn push_async_owned_row_width_device_slice<B>(
    launch: &mut cuda_async::simt::launch::AsyncKernelLaunchBuilder<'_>,
    bound: &mut RowWidthOwned<B>,
) where
    B: KernelSliceArgMut,
{
    launch.push_scalar_arg(bound.buffer.cu_deviceptr());
    launch.push_scalar_arg(bound.buffer.len() as u64);
    launch.push_scalar_arg(bound.width);
}

#[doc(hidden)]
#[cfg(feature = "async")]
pub fn load_cuda_module_from_async_context<F, R>(
    device_id: usize,
    f: F,
) -> Result<R, cuda_async::simt::error::DeviceError>
where
    F: FnOnce(&Arc<cuda_core::CudaContext>) -> Result<R, crate::EmbeddedModuleError>,
{
    cuda_async::simt::device_context::with_cuda_context(device_id, |ctx| f(ctx))?.map_err(|error| {
        if let crate::EmbeddedModuleError::Driver(error) = error {
            cuda_async::simt::error::DeviceError::Driver(error)
        } else {
            cuda_async::simt::error::DeviceError::KernelCache(error.to_string())
        }
    })
}

/// Async-context counterpart of [`crate::load_kernel_module`].
///
/// Loads a kernel module by stem name on `device_id`, using the async device
/// context map to find the underlying [`cuda_core::CudaContext`].
#[cfg(feature = "async")]
pub fn load_kernel_module_async(
    name: &str,
    device_id: usize,
) -> Result<Arc<cuda_core::CudaModule>, cuda_async::simt::error::DeviceError> {
    cuda_async::simt::device_context::with_cuda_context(device_id, |ctx| {
        crate::ltoir::load_kernel_module(ctx, name)
            .map_err(|error| cuda_async::simt::error::DeviceError::KernelCache(error.to_string()))
    })?
}

// =============================================================================
// Argument Wrapper Types
// =============================================================================

/// Wrapper for scalar values that need to be passed to kernels.
///
/// This wrapper exists for documentation purposes and to make the intent clear.
/// The macro handles unwrapping these properly.
///
/// # Example
///
/// ```ignore
/// // SAFETY: args match `scale`'s signature.
/// unsafe {
///     cuda_launch! {
///         kernel: scale,
///         // ...
///         args: (Scalar(factor), &input_dev, &mut output_dev)
///     }
/// }
/// ```
pub struct Scalar<T>(pub T);

/// Wrapper indicating a device buffer is read-only in the kernel.
///
/// # Example
///
/// ```ignore
/// // SAFETY: args match `transform`'s signature.
/// unsafe {
///     cuda_launch! {
///         kernel: transform,
///         // ...
///         args: (ReadOnly(&input_dev), &mut output_dev)
///     }
/// }
/// ```
pub struct ReadOnly<'a, T>(pub &'a T);

/// Wrapper indicating a device buffer is write-only in the kernel.
///
/// This is a hint for future optimizations - currently treated same as mutable.
///
/// # Example
///
/// ```ignore
/// // SAFETY: args match `generate`'s signature.
/// unsafe {
///     cuda_launch! {
///         kernel: generate,
///         // ...
///         args: (WriteOnly(&mut output_dev),)
///     }
/// }
/// ```
pub struct WriteOnly<'a, T>(pub &'a mut T);

// =============================================================================
// Length Extraction (for slice kernels)
// =============================================================================

/// Trait for types that have a length (used to pass ptr+len to kernels).
pub trait HasLength {
    fn len(&self) -> usize;
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl<T> HasLength for cuda_core::DeviceBuffer<T> {
    fn len(&self) -> usize {
        self.len()
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::c_void;

    // Dummy kernel marker for testing
    struct TestKernelMarker;
    impl CudaKernel for TestKernelMarker {
        const PTX_NAME: &'static str = "test_kernel"; // Original function name
    }

    #[repr(C)]
    #[derive(Clone, Copy, Debug, PartialEq)]
    struct TestParams {
        scale: f32,
        bias: i32,
    }

    fn assert_kernel_scalar<T: KernelScalar>() {}

    #[test]
    fn test_ptx_name_lookup() {
        assert_eq!(TestKernelMarker::PTX_NAME, "test_kernel");
    }

    #[test]
    fn test_scalar_wrapper() {
        let s = Scalar(42i32);
        assert_eq!(s.0, 42);
    }

    #[test]
    fn test_kernel_scalar_accepts_copy_argument_kinds() {
        assert_kernel_scalar::<f32>();
        assert_kernel_scalar::<TestParams>();
        assert_kernel_scalar::<*const f32>();
        assert_kernel_scalar::<*mut f32>();

        let offset = 7u32;
        let copy_closure = move |x: u32| x + offset;
        fn assert_value_is_kernel_scalar<T: KernelScalar>(_value: T) {}
        assert_value_is_kernel_scalar(copy_closure);
    }

    #[test]
    fn test_push_kernel_scalar_records_argument_address() {
        let mut args = Vec::new();
        let mut params = TestParams {
            scale: 1.5,
            bias: -2,
        };
        let expected = &mut params as *mut TestParams as *mut c_void;

        push_kernel_scalar(&mut args, &mut params);

        assert_eq!(args, vec![expected]);
        assert_eq!(unsafe { *(args[0] as *const TestParams) }, params);
    }

    #[test]
    fn test_push_kernel_scalar_accepts_copy_closure() {
        let mut args = Vec::new();
        let offset = 3u32;
        let mut copy_closure = move |x: u32| x + offset;
        let expected = &mut copy_closure as *mut _ as *mut c_void;

        push_kernel_scalar(&mut args, &mut copy_closure);

        assert_eq!(args, vec![expected]);
    }

    #[test]
    fn test_push_kernel_scalar_accepts_raw_pointer() {
        let mut args = Vec::new();
        let value = 42f32;
        let mut ptr = &value as *const f32;

        push_kernel_scalar(&mut args, &mut ptr);

        assert_eq!(args.len(), 1);
        assert_eq!(unsafe { *(args[0] as *const *const f32) }, ptr);
    }

    #[test]
    fn test_push_kernel_device_slice_records_pointer_and_len() {
        let mut args = Vec::new();
        let mut ptr: cuda_core::sys::CUdeviceptr = 0xfeed_beefu64;
        let mut len = 1024u64;

        push_kernel_device_slice(&mut args, &mut ptr, &mut len);

        assert_eq!(args.len(), 2);
        assert_eq!(
            unsafe { *(args[0] as *const cuda_core::sys::CUdeviceptr) },
            ptr
        );
        assert_eq!(unsafe { *(args[1] as *const u64) }, len);
    }
}
